version: '3.8'

services:
  bus-tracker:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
    restart: always
    shm_size: '2gb'

    environment:
      - TZ=Asia/Novosibirsk
      - PYTHONUNBUFFERED=1